// Code generated by github.com/atombender/go-jsonschema, DO NOT EDIT.

package schema

import "encoding/json"
import "fmt"
import "github.com/go-viper/mapstructure/v2"
import "reflect"
import "regexp"
import "strings"
import "unicode/utf8"

type BorderEdge struct {
	// Color corresponds to the JSON schema field "color".
	Color *string `json:"color,omitempty,omitzero" yaml:"color,omitempty" mapstructure:"color,omitempty"`

	// Style corresponds to the JSON schema field "style".
	Style *BorderLineStyle `json:"style,omitempty,omitzero" yaml:"style,omitempty" mapstructure:"style,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type BorderLineStyle string

const BorderLineStyleDashed BorderLineStyle = "dashed"
const BorderLineStyleDotted BorderLineStyle = "dotted"
const BorderLineStyleDouble BorderLineStyle = "double"
const BorderLineStyleMedium BorderLineStyle = "medium"
const BorderLineStyleNone BorderLineStyle = "none"
const BorderLineStyleThick BorderLineStyle = "thick"
const BorderLineStyleThin BorderLineStyle = "thin"

var enumValues_BorderLineStyle = []interface{}{
	"none",
	"thin",
	"medium",
	"thick",
	"dashed",
	"dotted",
	"double",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *BorderLineStyle) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_BorderLineStyle {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_BorderLineStyle, v)
	}
	*j = BorderLineStyle(v)
	return nil
}

type CSVXFormulaCell struct {
	// Cached corresponds to the JSON schema field "cached".
	Cached *Value `json:"cached,omitempty,omitzero" yaml:"cached,omitempty" mapstructure:"cached,omitempty"`

	// Formula corresponds to the JSON schema field "formula".
	Formula string `json:"formula" yaml:"formula" mapstructure:"formula"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXFormulaCell) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["formula"]; raw != nil && !ok {
		return fmt.Errorf("field formula in CSVXFormulaCell: required")
	}
	type Plain CSVXFormulaCell
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^=`, string(plain.Formula)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Formula", `^=`)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXFormulaCell(plain)
	return nil
}

type CSVXManifest struct {
	// Files corresponds to the JSON schema field "files".
	Files []string `json:"files" yaml:"files" mapstructure:"files"`

	// Format corresponds to the JSON schema field "format".
	Format interface{} `json:"format" yaml:"format" mapstructure:"format"`

	// Version corresponds to the JSON schema field "version".
	Version interface{} `json:"version" yaml:"version" mapstructure:"version"`

	// Workbook corresponds to the JSON schema field "workbook".
	Workbook string `json:"workbook" yaml:"workbook" mapstructure:"workbook"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXManifest) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["files"]; raw != nil && !ok {
		return fmt.Errorf("field files in CSVXManifest: required")
	}
	if _, ok := raw["format"]; raw != nil && !ok {
		return fmt.Errorf("field format in CSVXManifest: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in CSVXManifest: required")
	}
	if _, ok := raw["workbook"]; raw != nil && !ok {
		return fmt.Errorf("field workbook in CSVXManifest: required")
	}
	type Plain CSVXManifest
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Workbook != "workbook.json" {
		return fmt.Errorf("field %s: must be equal to %s", "workbook", "workbook.json")
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXManifest(plain)
	return nil
}

type CSVXSheetMetadata struct {
	// Cells corresponds to the JSON schema field "cells".
	Cells CSVXSheetMetadataCells `json:"cells,omitempty,omitzero" yaml:"cells,omitempty" mapstructure:"cells,omitempty"`

	// Columns corresponds to the JSON schema field "columns".
	Columns []Column `json:"columns,omitempty,omitzero" yaml:"columns,omitempty" mapstructure:"columns,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id *Id `json:"id,omitempty,omitzero" yaml:"id,omitempty" mapstructure:"id,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Row height by 1-based row number, in points (XLSX's own unit; its default row
	// height is 15pt) — see spec/03-sheets.md.
	RowHeights CSVXSheetMetadataRowHeights `json:"rowHeights,omitempty,omitzero" yaml:"rowHeights,omitempty" mapstructure:"rowHeights,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CSVXSheetMetadataCells map[string]Cell

// Row height by 1-based row number, in points (XLSX's own unit; its default row
// height is 15pt) — see spec/03-sheets.md.
type CSVXSheetMetadataRowHeights map[string]float64

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXSheetMetadata) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain CSVXSheetMetadata
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Name != nil && utf8.RuneCountInString(string(*plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if plain.Name != nil && utf8.RuneCountInString(string(*plain.Name)) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "name", 255)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXSheetMetadata(plain)
	return nil
}

type CSVXStyles struct {
	// Styles corresponds to the JSON schema field "styles".
	Styles []CSVXStylesStylesElem `json:"styles" yaml:"styles" mapstructure:"styles"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CSVXStylesStylesElem struct {
	// Alignment corresponds to the JSON schema field "alignment".
	Alignment CSVXStylesStylesElemAlignment `json:"alignment,omitempty,omitzero" yaml:"alignment,omitempty" mapstructure:"alignment,omitempty"`

	// Border corresponds to the JSON schema field "border".
	Border *CSVXStylesStylesElemBorder `json:"border,omitempty,omitzero" yaml:"border,omitempty" mapstructure:"border,omitempty"`

	// Fill corresponds to the JSON schema field "fill".
	Fill CSVXStylesStylesElemFill `json:"fill,omitempty,omitzero" yaml:"fill,omitempty" mapstructure:"fill,omitempty"`

	// Font corresponds to the JSON schema field "font".
	Font CSVXStylesStylesElemFont `json:"font,omitempty,omitzero" yaml:"font,omitempty" mapstructure:"font,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// NumberFormat corresponds to the JSON schema field "numberFormat".
	NumberFormat *string `json:"numberFormat,omitempty,omitzero" yaml:"numberFormat,omitempty" mapstructure:"numberFormat,omitempty"`

	// Protection corresponds to the JSON schema field "protection".
	Protection CSVXStylesStylesElemProtection `json:"protection,omitempty,omitzero" yaml:"protection,omitempty" mapstructure:"protection,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CSVXStylesStylesElemAlignment map[string]interface{}

type CSVXStylesStylesElemBorder struct {
	// Bottom corresponds to the JSON schema field "bottom".
	Bottom *BorderEdge `json:"bottom,omitempty,omitzero" yaml:"bottom,omitempty" mapstructure:"bottom,omitempty"`

	// Color corresponds to the JSON schema field "color".
	Color *string `json:"color,omitempty,omitzero" yaml:"color,omitempty" mapstructure:"color,omitempty"`

	// Left corresponds to the JSON schema field "left".
	Left *BorderEdge `json:"left,omitempty,omitzero" yaml:"left,omitempty" mapstructure:"left,omitempty"`

	// Right corresponds to the JSON schema field "right".
	Right *BorderEdge `json:"right,omitempty,omitzero" yaml:"right,omitempty" mapstructure:"right,omitempty"`

	// Style corresponds to the JSON schema field "style".
	Style *BorderLineStyle `json:"style,omitempty,omitzero" yaml:"style,omitempty" mapstructure:"style,omitempty"`

	// Top corresponds to the JSON schema field "top".
	Top *BorderEdge `json:"top,omitempty,omitzero" yaml:"top,omitempty" mapstructure:"top,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CSVXStylesStylesElemFill map[string]interface{}

type CSVXStylesStylesElemFont map[string]interface{}

type CSVXStylesStylesElemProtection map[string]interface{}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXStylesStylesElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in CSVXStylesStylesElem: required")
	}
	type Plain CSVXStylesStylesElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Za-z][A-Za-z0-9_-]{0,63}$`, string(plain.Id)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Id", `^[A-Za-z][A-Za-z0-9_-]{0,63}$`)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXStylesStylesElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXStyles) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["styles"]; raw != nil && !ok {
		return fmt.Errorf("field styles in CSVXStyles: required")
	}
	type Plain CSVXStyles
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXStyles(plain)
	return nil
}

type CSVXWorkbook struct {
	// Calculation corresponds to the JSON schema field "calculation".
	Calculation *CSVXWorkbookCalculation `json:"calculation,omitempty,omitzero" yaml:"calculation,omitempty" mapstructure:"calculation,omitempty"`

	// Id corresponds to the JSON schema field "id".
	Id Id `json:"id" yaml:"id" mapstructure:"id"`

	// Sheets corresponds to the JSON schema field "sheets".
	Sheets []CSVXWorkbookSheetsElem `json:"sheets" yaml:"sheets" mapstructure:"sheets"`

	// Version corresponds to the JSON schema field "version".
	Version interface{} `json:"version" yaml:"version" mapstructure:"version"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CSVXWorkbookCalculation struct {
	// Iteration corresponds to the JSON schema field "iteration".
	Iteration *bool `json:"iteration,omitempty,omitzero" yaml:"iteration,omitempty" mapstructure:"iteration,omitempty"`

	// Mode corresponds to the JSON schema field "mode".
	Mode *CSVXWorkbookCalculationMode `json:"mode,omitempty,omitzero" yaml:"mode,omitempty" mapstructure:"mode,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type CSVXWorkbookCalculationMode string

const CSVXWorkbookCalculationModeAutomatic CSVXWorkbookCalculationMode = "automatic"
const CSVXWorkbookCalculationModeManual CSVXWorkbookCalculationMode = "manual"
const CSVXWorkbookCalculationModeOnLoad CSVXWorkbookCalculationMode = "on-load"

var enumValues_CSVXWorkbookCalculationMode = []interface{}{
	"automatic",
	"manual",
	"on-load",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXWorkbookCalculationMode) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_CSVXWorkbookCalculationMode {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_CSVXWorkbookCalculationMode, v)
	}
	*j = CSVXWorkbookCalculationMode(v)
	return nil
}

type CSVXWorkbookSheetsElem struct {
	// Id corresponds to the JSON schema field "id".
	Id Id `json:"id" yaml:"id" mapstructure:"id"`

	// Metadata corresponds to the JSON schema field "metadata".
	Metadata *string `json:"metadata,omitempty,omitzero" yaml:"metadata,omitempty" mapstructure:"metadata,omitempty"`

	// Name corresponds to the JSON schema field "name".
	Name string `json:"name" yaml:"name" mapstructure:"name"`

	// Path corresponds to the JSON schema field "path".
	Path string `json:"path" yaml:"path" mapstructure:"path"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXWorkbookSheetsElem) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in CSVXWorkbookSheetsElem: required")
	}
	if _, ok := raw["name"]; raw != nil && !ok {
		return fmt.Errorf("field name in CSVXWorkbookSheetsElem: required")
	}
	if _, ok := raw["path"]; raw != nil && !ok {
		return fmt.Errorf("field path in CSVXWorkbookSheetsElem: required")
	}
	type Plain CSVXWorkbookSheetsElem
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Metadata != nil {
		if matched, _ := regexp.MatchString(`^sheets/[A-Za-z][A-Za-z0-9_-]{0,63}\.meta\.json$`, string(*plain.Metadata)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "Metadata", `^sheets/[A-Za-z][A-Za-z0-9_-]{0,63}\.meta\.json$`)
		}
	}
	if utf8.RuneCountInString(string(plain.Name)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "name", 1)
	}
	if utf8.RuneCountInString(string(plain.Name)) > 255 {
		return fmt.Errorf("field %s length: must be <= %d", "name", 255)
	}
	if matched, _ := regexp.MatchString(`^sheets/[A-Za-z][A-Za-z0-9_-]{0,63}\.csv$`, string(plain.Path)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "Path", `^sheets/[A-Za-z][A-Za-z0-9_-]{0,63}\.csv$`)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXWorkbookSheetsElem(plain)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *CSVXWorkbook) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in CSVXWorkbook: required")
	}
	if _, ok := raw["sheets"]; raw != nil && !ok {
		return fmt.Errorf("field sheets in CSVXWorkbook: required")
	}
	if _, ok := raw["version"]; raw != nil && !ok {
		return fmt.Errorf("field version in CSVXWorkbook: required")
	}
	type Plain CSVXWorkbook
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Sheets != nil && len(plain.Sheets) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "sheets", 1)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = CSVXWorkbook(plain)
	return nil
}

type Cell struct {
	// Cached corresponds to the JSON schema field "cached".
	Cached *Value `json:"cached,omitempty,omitzero" yaml:"cached,omitempty" mapstructure:"cached,omitempty"`

	// Formula corresponds to the JSON schema field "formula".
	Formula *string `json:"formula,omitempty,omitzero" yaml:"formula,omitempty" mapstructure:"formula,omitempty"`

	// Style corresponds to the JSON schema field "style".
	Style *Id `json:"style,omitempty,omitzero" yaml:"style,omitempty" mapstructure:"style,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *ScalarType `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// Validation corresponds to the JSON schema field "validation".
	Validation *Validation `json:"validation,omitempty,omitzero" yaml:"validation,omitempty" mapstructure:"validation,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Cell) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	type Plain Cell
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if plain.Formula != nil {
		if matched, _ := regexp.MatchString(`^=`, string(*plain.Formula)); !matched {
			return fmt.Errorf("field %s pattern match: must match %s", "Formula", `^=`)
		}
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = Cell(plain)
	return nil
}

type Column struct {
	// Id corresponds to the JSON schema field "id".
	Id string `json:"id" yaml:"id" mapstructure:"id"`

	// Name corresponds to the JSON schema field "name".
	Name *string `json:"name,omitempty,omitzero" yaml:"name,omitempty" mapstructure:"name,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *ScalarType `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	// XLSX character-width units (the number of '0' glyphs, in the workbook's default
	// font, that fit the column, plus padding) — see spec/03-sheets.md for the
	// canonical pixel conversion formula every engine must use.
	Width *float64 `json:"width,omitempty,omitzero" yaml:"width,omitempty" mapstructure:"width,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Column) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["id"]; raw != nil && !ok {
		return fmt.Errorf("field id in Column: required")
	}
	type Plain Column
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if utf8.RuneCountInString(string(plain.Id)) < 1 {
		return fmt.Errorf("field %s length: must be >= %d", "id", 1)
	}
	if plain.Width != nil && 0 >= *plain.Width {
		return fmt.Errorf("field %s: must be > %v", "width", 0)
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = Column(plain)
	return nil
}

type Id string

// UnmarshalJSON implements json.Unmarshaler.
func (j *Id) UnmarshalJSON(value []byte) error {
	type Plain Id
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	if matched, _ := regexp.MatchString(`^[A-Za-z][A-Za-z0-9_-]{0,63}$`, string(plain)); !matched {
		return fmt.Errorf("field %s pattern match: must match %s", "", `^[A-Za-z][A-Za-z0-9_-]{0,63}$`)
	}
	*j = Id(plain)
	return nil
}

type ScalarType string

const ScalarTypeBlank ScalarType = "blank"
const ScalarTypeBoolean ScalarType = "boolean"
const ScalarTypeDate ScalarType = "date"
const ScalarTypeDatetime ScalarType = "datetime"
const ScalarTypeDecimal ScalarType = "decimal"
const ScalarTypeError ScalarType = "error"
const ScalarTypeInteger ScalarType = "integer"
const ScalarTypeString ScalarType = "string"
const ScalarTypeTime ScalarType = "time"

var enumValues_ScalarType = []interface{}{
	"blank",
	"boolean",
	"integer",
	"decimal",
	"string",
	"date",
	"time",
	"datetime",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ScalarType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ScalarType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ScalarType, v)
	}
	*j = ScalarType(v)
	return nil
}

type Validation struct {
	// AllowBlank corresponds to the JSON schema field "allowBlank".
	AllowBlank *bool `json:"allowBlank,omitempty,omitzero" yaml:"allowBlank,omitempty" mapstructure:"allowBlank,omitempty"`

	// Formula1 corresponds to the JSON schema field "formula1".
	Formula1 *string `json:"formula1,omitempty,omitzero" yaml:"formula1,omitempty" mapstructure:"formula1,omitempty"`

	// Formula2 corresponds to the JSON schema field "formula2".
	Formula2 *string `json:"formula2,omitempty,omitzero" yaml:"formula2,omitempty" mapstructure:"formula2,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Operator corresponds to the JSON schema field "operator".
	Operator *string `json:"operator,omitempty,omitzero" yaml:"operator,omitempty" mapstructure:"operator,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type *ValidationType `json:"type,omitempty,omitzero" yaml:"type,omitempty" mapstructure:"type,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ValidationType string

const ValidationTypeCustom ValidationType = "custom"
const ValidationTypeDate ValidationType = "date"
const ValidationTypeDecimal ValidationType = "decimal"
const ValidationTypeList ValidationType = "list"
const ValidationTypeTextLength ValidationType = "textLength"
const ValidationTypeWhole ValidationType = "whole"

var enumValues_ValidationType = []interface{}{
	"whole",
	"decimal",
	"list",
	"date",
	"textLength",
	"custom",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ValidationType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ValidationType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ValidationType, v)
	}
	*j = ValidationType(v)
	return nil
}

type Value struct {
	// Code corresponds to the JSON schema field "code".
	Code *string `json:"code,omitempty,omitzero" yaml:"code,omitempty" mapstructure:"code,omitempty"`

	// Message corresponds to the JSON schema field "message".
	Message *string `json:"message,omitempty,omitzero" yaml:"message,omitempty" mapstructure:"message,omitempty"`

	// Type corresponds to the JSON schema field "type".
	Type ValueType `json:"type" yaml:"type" mapstructure:"type"`

	// Value corresponds to the JSON schema field "value".
	Value interface{} `json:"value,omitempty,omitzero" yaml:"value,omitempty" mapstructure:"value,omitempty"`

	AdditionalProperties interface{} `mapstructure:",remain"`
}

type ValueType string

const ValueTypeBlank ValueType = "blank"
const ValueTypeBoolean ValueType = "boolean"
const ValueTypeDate ValueType = "date"
const ValueTypeDatetime ValueType = "datetime"
const ValueTypeDecimal ValueType = "decimal"
const ValueTypeError ValueType = "error"
const ValueTypeInteger ValueType = "integer"
const ValueTypeString ValueType = "string"
const ValueTypeTime ValueType = "time"

var enumValues_ValueType = []interface{}{
	"blank",
	"boolean",
	"integer",
	"decimal",
	"string",
	"date",
	"time",
	"datetime",
	"error",
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *ValueType) UnmarshalJSON(value []byte) error {
	var v string
	if err := json.Unmarshal(value, &v); err != nil {
		return err
	}
	var ok bool
	for _, expected := range enumValues_ValueType {
		if reflect.DeepEqual(v, expected) {
			ok = true
			break
		}
	}
	if !ok {
		return fmt.Errorf("invalid value (expected one of %#v): %#v", enumValues_ValueType, v)
	}
	*j = ValueType(v)
	return nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (j *Value) UnmarshalJSON(value []byte) error {
	var raw map[string]interface{}
	if err := json.Unmarshal(value, &raw); err != nil {
		return err
	}
	if _, ok := raw["type"]; raw != nil && !ok {
		return fmt.Errorf("field type in Value: required")
	}
	type Plain Value
	var plain Plain
	if err := json.Unmarshal(value, &plain); err != nil {
		return err
	}
	st := reflect.TypeOf(Plain{})
	for i := range st.NumField() {
		delete(raw, st.Field(i).Name)
		delete(raw, strings.Split(st.Field(i).Tag.Get("json"), ",")[0])
	}
	if err := mapstructure.Decode(raw, &plain.AdditionalProperties); err != nil {
		return err
	}
	*j = Value(plain)
	return nil
}
